-- INSERT INTO "Types" VALUES ('LEADER_ALEXANDER_GREECE',578691269,'KIND_LEADER');

-- INSERT INTO "Leaders" VALUES ('LEADER_ALEXANDER_GREECE','LOC_LEADER_ALEXANDER_NAME',NULL,0,'LEADER_DEFAULT',4,'Male',50);

-- INSERT INTO "LeaderQuotes" VALUES ('LEADER_ALEXANDER_GREECE','LOC_PEDIA_LEADERS_PAGE_LEADER_ALEXANDER_QUOTE','MACE_AL_MISC_PEP_TALK_D');



-- INSERT INTO "HistoricalAgendas" VALUES ('LEADER_ALEXANDER_GREECE','AGENDA_SHORT_LIFE_GLORY');

-- INSERT INTO "LeaderTraits" VALUES ('LEADER_ALEXANDER_GREECE','TRAIT_LEADER_TO_WORLDS_END');
-- INSERT INTO "LeaderTraits" VALUES ('LEADER_ALEXANDER_GREECE','TRAIT_LEADER_UNIT_HETAIROI');
-- INSERT INTO "LeaderTraits" VALUES ('LEADER_ALEXANDER_GREECE','TRAIT_LEADER_LOW_RELIGIOUS_PREFERENCE');
-- INSERT INTO "LeaderTraits" VALUES ('LEADER_ALEXANDER_GREECE','TRAIT_LEADER_AGGRESSIVE_MILITARY');

-- INSERT INTO "CivilizationLeaders" VALUES ('LEADER_ALEXANDER_GREECE','CIVILIZATION_MACEDON','LOC_CITY_NAME_PELLA');

INSERT INTO PlayerColors	
		(Type,					Usage,		PrimaryColor, 									SecondaryColor,									Alt1PrimaryColor, Alt1SecondaryColor, Alt2PrimaryColor, Alt2SecondaryColor, Alt3PrimaryColor, Alt3SecondaryColor)
SELECT	'LEADER_ALEXANDER_GREECE',	'Unique',	PrimaryColor,	SecondaryColor,	Alt1PrimaryColor, Alt1SecondaryColor, Alt2PrimaryColor, Alt2SecondaryColor, Alt3PrimaryColor, Alt3SecondaryColor
FROM PlayerColors WHERE Type = 'LEADER_ALEXANDER';