-- INSERT INTO "Types" VALUES ('LEADER_ALEXANDER_GREECE',578691269,'KIND_LEADER');

-- INSERT INTO "Leaders" VALUES ('LEADER_ALEXANDER_GREECE','LOC_LEADER_ALEXANDER_NAME',NULL,0,'LEADER_DEFAULT',4,'Male',50);

-- INSERT INTO "LeaderQuotes" VALUES ('LEADER_ALEXANDER_GREECE','LOC_PEDIA_LEADERS_PAGE_LEADER_ALEXANDER_QUOTE','MACE_AL_MISC_PEP_TALK_D');



-- INSERT INTO "HistoricalAgendas" VALUES ('LEADER_ALEXANDER_GREECE','AGENDA_SHORT_LIFE_GLORY');

-- INSERT INTO "LeaderTraits" VALUES ('LEADER_ALEXANDER_GREECE','TRAIT_LEADER_TO_WORLDS_END');
-- INSERT INTO "LeaderTraits" VALUES ('LEADER_ALEXANDER_GREECE','TRAIT_LEADER_UNIT_HETAIROI');
-- INSERT INTO "LeaderTraits" VALUES ('LEADER_ALEXANDER_GREECE','TRAIT_LEADER_LOW_RELIGIOUS_PREFERENCE');
-- INSERT INTO "LeaderTraits" VALUES ('LEADER_ALEXANDER_GREECE','TRAIT_LEADER_AGGRESSIVE_MILITARY');

-- INSERT INTO "CivilizationLeaders" VALUES ('LEADER_ALEXANDER_GREECE','CIVILIZATION_MACEDON','LOC_CITY_NAME_PELLA');



INSERT INTO Types	
		(Type,							Kind)
VALUES	('LEADER_ALEXANDER_GREECE',	'KIND_LEADER');


INSERT INTO Leaders	
		(LeaderType,					Name,										InheritFrom,		SceneLayers, Sex, SameSexPercentage)
VALUES	('LEADER_ALEXANDER_GREECE',	'LOC_LEADER_ALEXANDER_GREECE_NAME',		'LEADER_DEFAULT',	4, 'Male', '50');	



INSERT INTO LeaderQuotes	
		(LeaderType,			Quote, QuoteAudio)
VALUES	('LEADER_ALEXANDER_GREECE',	'LOC_PEDIA_LEADERS_PAGE_LEADER_ALEXANDER_GREECE_QUOTE', 'MACE_AL_MISC_PEP_TALK_D');	


INSERT INTO HistoricalAgendas
		(LeaderType,				AgendaType)
VALUES	('LEADER_ALEXANDER_GREECE',	'AGENDA_SHORT_LIFE_GLORY');


INSERT INTO LeaderTraits	
		(LeaderType,			TraitType)
VALUES	('LEADER_ALEXANDER_GREECE',	'TRAIT_LEADER_TO_WORLDS_END'),
		('LEADER_ALEXANDER_GREECE',	'TRAIT_LEADER_UNIT_HETAIROI'),
		('LEADER_ALEXANDER_GREECE', 'TRAIT_LEADER_LOW_RELIGIOUS_PREFERENCE'),
		('LEADER_ALEXANDER_GREECE', 'TRAIT_LEADER_AGGRESSIVE_MILITARY');


INSERT INTO CivilizationLeaders	
		(CivilizationType,					LeaderType,										CapitalName)
VALUES	('CIVILIZATION_GREECE',	'LEADER_ALEXANDER_GREECE',	'LOC_CITY_NAME_PELLA');	

INSERT INTO LoadingInfo	
		(LeaderType,				BackgroundImage,			ForegroundImage,					PlayDawnOfManAudio)
VALUES	('LEADER_ALEXANDER_GREECE',	'LEADER_ALEXANDER_BACKGROUND',	'LEADER_ALEXANDER_NEUTRAL',		1);